"""empty message

Revision ID: 4b7feda84ee1
Revises: 4256a41d082f
Create Date: 2021-07-17 00:19:07.589047

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7feda84ee1'
down_revision = '4256a41d082f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_available_datetimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('available_start_time', sa.DateTime(), nullable=False),
    sa.Column('available_end_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('shows', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

    op.execute('UPDATE shows SET end_time = ' + datetime.now().strftime("'%Y-%m-%d %H:%M:%S'") +  ' WHERE end_time IS NULL;')
    op.alter_column('shows', 'end_time', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'end_time')
    op.drop_table('artist_available_datetimes')
    # ### end Alembic commands ###
