"""empty message

Revision ID: 72c27990fe5f
Revises: 7a4a220fc369
Create Date: 2021-07-15 06:29:16.794416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c27990fe5f'
down_revision = '7a4a220fc369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('venue_genres_venue_id_fkey', 'venue_genres', type_='foreignkey')
    op.drop_constraint('venue_genres_genre_fkey', 'venue_genres', type_='foreignkey')
    op.create_foreign_key(None, 'venue_genres', 'Venue', ['venue_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'venue_genres', 'Genre', ['genre'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.drop_constraint(None, 'venue_genres', type_='foreignkey')
    op.create_foreign_key('venue_genres_genre_fkey', 'venue_genres', 'Genre', ['genre'], ['name'])
    op.create_foreign_key('venue_genres_venue_id_fkey', 'venue_genres', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
