"""empty message

Revision ID: 7a4a220fc369
Revises: 
Create Date: 2021-07-15 06:19:59.935860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '7a4a220fc369'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Genre',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['genre'], ['Genre.name'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genre')
    )
    # ### end Alembic commands ###

    genre_table = table (
        'Genre',
        column('name', String)
    )
    genres = [
        {'name': 'Alternative'},
        {'name': 'Blues'},
        {'name': 'Classical'},
        {'name': 'Country'},
        {'name': 'Electronic'},
        {'name': 'Folk'},
        {'name': 'Funk'},
        {'name': 'Hip-Hop'},
        {'name': 'Heavy Metal'},
        {'name': 'Instrumental'},
        {'name': 'Jazz'},
        {'name': 'Musical Theatre'},
        {'name': 'Pop'},
        {'name': 'Punk'},
        {'name': 'R&B'},
        {'name': 'Reggae'},
        {'name': 'Rock n Roll'},
        {'name': 'Soul'},
        {'name': 'Other'},
    ]
    op.bulk_insert(
        genre_table,
        genres
    )

def downgrade():
    op.drop_table('venue_genres')
    op.drop_table('Venue')
    op.drop_table('Genre')
    op.drop_table('Artist')
