"""empty message

Revision ID: a24d044dcd0e
Revises: 4b7feda84ee1
Create Date: 2021-07-17 00:50:48.803317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a24d044dcd0e'
down_revision = '4b7feda84ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_available_datetimes', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('artist_available_datetimes', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_column('artist_available_datetimes', 'available_end_time')
    op.drop_column('artist_available_datetimes', 'available_start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist_available_datetimes', sa.Column('available_start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('artist_available_datetimes', sa.Column('available_end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('artist_available_datetimes', 'end_time')
    op.drop_column('artist_available_datetimes', 'start_time')
    # ### end Alembic commands ###
